### ISSUE TITLE
Low resolution background in client settings

### ISSUE THREAD

**Issue by CommanderAnime** [Gatohost/gatoclient#1]
**Describe the bug**
Poor, low-resolution background in Gatoclient settings

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the application.
2. Press the Gato logo.
3. Note the background resolution.

**Expected behaviour**
Clear, sharp background image

**Screenshots**
![image](https://user-images.githubusercontent.com/49583904/144256813-1c95a4ef-7c67-47e9-adca-183c76ba6e6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0

**Comment by creepycats** [comment]
Lmao it isnt high res cause I dont load it from the files. its a github loaded css so I have to use links and the version I used there was shrunk. Ill fix it rn
