### ISSUE TITLE
adjustments to the clients setting icon

### ISSUE THREAD

**Issue by nxxh447** [Gatohost/gatoclient#10]
**Is your feature request related to a problem? Please describe.**
gato client `menuItem` is ugly as shit, be a normal client and follow my suggestion below

**Describe the solution you'd like**
remove the gato client `menuItem` and instead have it be a tab inside the settings window like other clients.

**Describe alternatives you've considered**
N/A

**Comment by nxxh447** [comment]
(kinda a modified version of what @CommanderAnime said)

**Comment by CommanderAnime** [comment]
**Describe alternatives you've considered**
Prettier icon lmao

**Comment by creepycats** [comment]
**Describe alternatives you've considered**
Idk you try hiring a graphic designer yourself.

Also its literally a tab in the client settings, I just like having the button as a way to show people who use the client at a glance.

If I *really* need to get rid of it I guess I can part ways or make a more general icon but for now nah

**Comment by nxxh447** [comment]
its not what the icon looks like (your gfx works top mine easily)
its that it doesn't look right having it on the menuBar
