### ISSUE TITLE
Addons Won't Download

### ISSUE THREAD

**Issue by GorbClan** [Gatohost/gatoclient#19]
I'm playing on the Linux and the add-ons say downloaded in the top left of the hub but when i return to the settings it says no add-ons downloaded.

**Comment by helloimsome1** [comment]
I can install all the addons but when I refresh it doesn't download/save.

**Comment by jacobofbrooklyn** [comment]
For anyone seeing this: This is fixed in the new version of the client. Join the discord for bug reports and suggestions

**Comment by gatodevelowoper** [comment]
Should be fixed. Update client.
