### ISSUE TITLE
Wrong client setting tab

### ISSUE THREAD

**Issue by CommanderAnime** [Gatohost/gatoclient#2]
**Describe the bug**
The last tab in settings gets labelled and redirects to client. CSS/margins also get slightly changed as a result.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to settings via the settings
2. Press any tab that isn't the Gato settings tab.
3. Note the Gato client has now changed to Client, alongside with its event listeners. The tab is empty.

**Expected behaviour**
Gato client setting should remain regardless what tab you navigate to.

**Screenshots**
https://user-images.githubusercontent.com/49583904/144258626-8c7ac68e-9442-4c5a-b62e-043fd069743c.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0

**Comment by creepycats** [comment]
Fixed :D
