### ISSUE TITLE
Preload reload background image

### ISSUE THREAD

**Issue by CommanderAnime** [Gatohost/gatoclient#3]
**Describe the bug**
Loading page background image should be preloaded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the client, reload the page, or join a new game.

**Expected behaviour**
The background image should be instantly loaded, as to avoid the grey background.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0

**Comment by creepycats** [comment]
Actually this is done because sometimes a CSS file would be overwritten. I am still working on a fix thing that will fix a lot of CSS bugs
