### ISSUE TITLE
Custom billboards do not replace image billboards

### ISSUE THREAD

**Issue by CommanderAnime** [Gatohost/gatoclient#4]
**Describe the bug**
Custom game billboards will only replace billboards with text, not image backgrounds such as FaceIt promotions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the client, ensure you have custom billboards enabled
2. Join a game, look for a billboard with an image (eg. FaceIt)

**Expected behaviour**
Custom billboards should override image billboards.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0

**Comment by creepycats** [comment]
Actually It was made to override text billboards before being replaced. I am working on a new method called Advanced Billboards that let you make your own image billboard ingame
