### ISSUE TITLE
Gato icon is draggable

### ISSUE THREAD

**Issue by CommanderAnime** [Gatohost/gatoclient#6]
**Describe the bug**
The Gato Client settings icon can be dragged as an image on user mousedown.

**To Reproduce**
1. Launch the application.
2. Mousedown the Gato Client settings icon
3. Drag it around

**Expected behaviour**
The icon should be static, undraggable like the rest of the side icons. An easy solution is to add ```
#gatoMenuItem > img.menBtnIcn {
    -webkit-user-select: none;
    -webkit-user-drag: none;
    -webkit-app-region: no-drag;
}
``` to `GatoClientElectron\app\settings\css\settings.css`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0

**Comment by creepycats** [comment]
TY for that easy fix.
